pipeline {
    agent any

    stages {
        stage('CI-Build') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh "docker login --username ${USERNAME} --password ${PASSWORD}"
                        sh "docker build -t new-nginx:v3 -f nginx/nginx/dockerfile ./nginx/nginx/"
                        sh "docker tag new-nginx:v3 azhn/nginx:v3"
                    }
                }
            }
        }
        stage('CI-PUsh') {
            steps {
                script {
                        sh "docker push azhn/nginx:v3"

                    }
                }
            }

        stage('CD') {
            steps {
                script {
                        sh "docker run -d -p 8065:80 --name nginx-test-con1 azhn/nginx:v3"
                    }
                }
            }
    }
}
