pipeline {
    agent any

    stages {
        stage('CI') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh "docker login --username ${USERNAME} --password ${PASSWORD}"
                        sh "docker build -t new-nginx:v2 -f ./nginx/dockerfile ./nginx"
                        sh "docker tag new-nginx:v2 azhn/nginx:v2"
                        sh "docker push azhn/nginx:v2"
                    }
                }
            }
        }

        stage('CD') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh "docker login --username ${USERNAME} --password ${PASSWORD}"
                        sh "docker run -d --name nginx-test-con azhn/nginx:v2"
                    }
                }
            }
        }
    }
}
